version: '3.8'

services:
  eventaro-db:
    image: postgres:15-alpine
    container_name: eventaro-postgres
    environment:
      - POSTGRES_DB=eventarodb
      - POSTGRES_USER=eventaro
      - POSTGRES_PASSWORD=adventure
    ports:
      - "5435:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: